stages:
  - build
  - test
  - distribute
  - build_image
  - test_image
  - release_image


image: registry.cnrgh.fr/images/sources/python-36-centos7:latest


variables:
  CI_IMAGE:      registry.cnrgh.fr/$CI_PROJECT_NAMESPACE/contatester/contatester
  DOCKER_DRIVER: overlay2
  LANG: en_US.UTF-8


build_contatester:
  stage: build
  tags:
    - nodind
  cache:
      key: py_lbi
      untracked: true
  before_script:
    - pip3 install setuptools wheel
    - pip3 install --upgrade pip
    - pip3 install --upgrade wheel
    - pip3 install --upgrade setuptools
  script:
    - cd contatester
    - python3 setup.py clean
    - python3 setup.py build


test_contatester:
  stage: test
  tags:
    - nodind
  cache:
      key: py_lbi
      untracked: true
  before_script:
    - pip3 install setuptools wheel
    - pip3 install --upgrade pip
    - pip3 install --upgrade wheel
    - pip3 install --upgrade setuptools
  script:
    - cd contatester
    - python3 setup.py test


coverage_contatester:
  stage: test
  tags:
    - nodind
  cache:
      key: py_lbi
      untracked: true
  artifacts:
    name: reports
    paths:
      - htmlcov
  before_script:
    - pip3 install setuptools wheel
    - pip3 install --upgrade pip
    - pip3 install --upgrade wheel
    - pip3 install --upgrade setuptools
  script:
    - cd contatester
    - pip3 install coverage
    - python3 setup.py coverage


wheel_contatester:
  stage: distribute
  tags:
    - nodind
  cache:
      key: py_lbi
      untracked: true
  artifacts:
    name: wheel
    paths:
      - dist
  before_script:
    - pip3 install setuptools wheel
    - pip3 install --upgrade pip
    - pip3 install --upgrade wheel
    - pip3 install --upgrade setuptools
  script:
    - cd contatester
    - python3 setup.py bdist_wheel

build_contatester_image:
  stage: build_image
  image: docker
  tags:
    - dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.cnrgh.fr
  script:
    - docker build --pull -t $CI_IMAGE:$CI_COMMIT_SHA  .
    - docker push $CI_IMAGE:$CI_COMMIT_SHA

test_contatester_image:
  stage: test_image
  image: docker
  tags:
    - dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.cnrgh.fr
  script:
    - docker pull $CI_IMAGE:$CI_COMMIT_SHA
    - docker images
    - docker run -v data_examples/test_1.vcf.gz:/test_1.vcf.gz \
                 -v data_examples/test_2.vcf.gz:/test_2.vcf.gz \
                 $CI_IMAGE:$CI_COMMIT_SHA -l data_examples/vcfs_list.txt

release_image:
  stage: test_image
  image: docker
  tags:
    - dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.cnrgh.fr
  script:
    - docker pull $CI_IMAGE:$CI_COMMIT_SHA
    - docker tag  $CI_IMAGE:$CI_COMMIT_SHA $CI_IMAGE:$CI_COMMIT_TAG
    - docker tag  $CI_IMAGE $CI_IMAGE:latest
    - docker push $CI_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_IMAGE:latest
  only:
    - tags