stages:
  - build
  - test
  - distribute
  - build_image
  - test_image
  - release_image


image: registry.cnrgh.fr/images/sources/python-36-centos7:latest


variables:
  CI_IMAGE: registry.cnrgh.fr/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_PROJECT_NAME:CI_COMMIT_SHA
  RELEASE_IMAGE: registry.cnrgh.fr/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_PROJECT_NAME
  DOCKER_DRIVER: overlay2
  LANG: en_US.UTF-8


build contatester:
  stage: build
  tags:
    - nodind
  cache:
      key: py_lbi
      untracked: true
  script:
    - cd contatester
    - python3 setup.py clean
    - python3 setup.py build


test contatester:
  stage: test
  tags:
    - nodind
  cache:
      key: py_lbi
      untracked: true
  script:
    - cd contatester
    - python3 setup.py test


coverage contatester:
  stage: test
  tags:
    - nodind
  cache:
      key: py_lbi
      untracked: true
  artifacts:
    name: reports
    paths:
      - htmlcov
  script:
    - cd contatester
    - pip install coverage
    - python3 setup.py coverage


wheel contatester:
  stage: distribute
  tags:
    - nodind
  cache:
      key: py_lbi
      untracked: true
  artifacts:
    name: wheel
    paths:
      - dist
  script:
    - cd contatester
    - python3 setup.py bdist_wheel

build contatester image:
  stage: build_image
  image: docker
  tags:
    - dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.cnrgh.fr
  script:
    - docker build --pull -t $CI_IMAGE  .
    - docker push $CI_IMAGE

test contatester image:
  stage: test_image
  image: docker
  tags:
    - dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.cnrgh.fr
  script:
    - docker pull $CI_IMAGE
    - docker run $CI_IMAGE

release image:
  stage: distribute
  image: docker
  tags:
    - dind
  dependencies:
    - test contatester image
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.cnrgh.fr
  script:
    - docker pull $CI_IMAGE
    - docker tag $CI_IMAGE $RELEASE_IMAGE:$CI_COMMIT_TAG
    - docker push $RELEASE_IMAGE:$CI_COMMIT_TAG
    - docker tag $CI_IMAGE $RELEASE_IMAGE:latest
    - docker push $RELEASE_IMAGE:latest
  only:
    - tags