stages:
  - build
  - test
  - distribute
  - build_image
  - test_image
  - distribute_image


image: registry.cnrgh.fr/images/sources/python-36-centos7:latest


variables:
    CI_IMAGE: registry.cnrgh.fr/lbi/python_starter_project/ci:1.0.0-0
    DOCKER_DRIVER: overlay2
    LANG: en_US.UTF-8


build contatester:
  stage: build
  tags:
    - nodind
  cache:
      key: py_lbi
      untracked: true
  script:
    - cd contatester
    - python36 setup.py clean
    - python36 setup.py build


test contatester:
  stage: test
  tags:
    - nodind
  cache:
      key: py_lbi
      untracked: true
  script:
    - cd contatester
    - python36 setup.py test


coverage contatester:
  stage: test
  tags:
    - nodind
  cache:
      key: py_lbi
      untracked: true
  artifacts:
    name: reports
    paths:
      - htmlcov
  script:
    - cd contatester
    - pip install coverage
    - python36 setup.py coverage


wheel contatester:
  stage: distribute
  tags:
    - nodind
  cache:
      key: py_lbi
      untracked: true
  artifacts:
    name: wheel
    paths:
      - dist
  script:
    - cd contatester
    - python36 setup.py bdist_wheel

build contatester image:
  stage: build_image
  image: docker
  tags:
    - dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.cnrgh.fr
  script:
    - docker build --pull -t $CI_IMAGE:$CI_COMMIT_SHA -t  $CI_IMAGE:latest .
    - docker push $CI_IMAGE:$CI_COMMIT_SHA

test contatester image:
  stage: test_image
  image: docker
  tags:
    - dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.cnrgh.fr
  script:
    - docker pull $CI_IMAGE:$CI_COMMIT_SHA
    - docker run $CI_IMAGE:$CI_COMMIT_SHA
