stages:
  - build
  - test
  - distribute
  - build_image
  - test_image
  - release_image


image: registry.cnrgh.fr/images/sources/python-36-centos7:latest


variables:
  DOCKER_DRIVER:        overlay2
  LANG:                 en_US.UTF-8
  CI_IMAGE:             registry.cnrgh.fr/$CI_PROJECT_NAMESPACE/contatester/contatester

.prepare_python_env:
  tags:
    - nodind
  cache:
      key: py_lbi
      untracked: true
  before_script:
    - pip3 install setuptools wheel
    - pip3 install --upgrade pip
    - pip3 install --upgrade wheel
    - pip3 install --upgrade setuptools

.docker_jobs:
  image: docker
  tags:
    - dind
  cache:
      key: docker_lbi
      untracked: true
  before_script:
  - eval export TODAY=$(date +'%Y%m%d')
  - eval export CI_SHORT_COMMIT_SHA="${CI_COMMIT_SHA:0:8}"
  - eval export TEST_IMAGE_TAG="${TODAY}_${CI_SHORT_COMMIT_SHA}"
  - eval export IMAGE_FILE="contatester-${TEST_IMAGE_TAG}.tar.gz"
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.cnrgh.fr

build_contatester:
  extends: .prepare_python_env
  stage: build
  script:
    - cd contatester
    - python3 setup.py clean
    - python3 setup.py build


test_contatester:
  extends: .prepare_python_env
  stage: test
  script:
    - cd contatester
    - python3 setup.py test


coverage_contatester:
  extends: .prepare_python_env
  stage: test
  artifacts:
    name: reports
    paths:
      - htmlcov
  script:
    - cd contatester
    - pip3 install coverage
    - python3 setup.py coverage


wheel_contatester:
  extends: .prepare_python_env
  stage: distribute
  artifacts:
    name: wheel
    paths:
      - dist
  script:
    - cd contatester
    - python3 setup.py bdist_wheel

build_contatester_image:
  stage: build_image
  extends: .docker_jobs
  artifacts:
    name: docker_image
    paths:
      - contatester-*.tar.gz
  script:
    - docker build --pull -t "${CI_IMAGE}:${TEST_IMAGE_TAG}" .
    - docker save "${CI_IMAGE}:${TEST_IMAGE_TAG}" | gzip -c > "${IMAGE_FILE}"
    - du -sh "${IMAGE_FILE}"

test_contatester_image:
  stage: test_image
  extends: .docker_jobs
  script:
    - docker load --input ${IMAGE_FILE}
    - |
      docker run --volume $(pwd)/data_examples/test_1.vcf.gz:/test_1.vcf.gz \
                 --volume $(pwd)/data_examples/test_2.vcf.gz:/test_2.vcf.gz \
                 "${CI_IMAGE}:${TEST_IMAGE_TAG}" -l data_examples/vcfs_list.txt

master_image:
  stage: release_image
  extends: .docker_jobs
  script:
    - docker load --input ${IMAGE_FILE}
    - docker tag  "${CI_IMAGE}:${TEST_IMAGE_TAG}" ${CI_IMAGE}:latest
    - docker push "${CI_IMAGE}:latest"
  only:
    - master

release_image:
  stage: release_image
  extends: .docker_jobs
  script:
    - docker load --input ${IMAGE_FILE}
    - docker tag  "${CI_IMAGE}:${TEST_IMAGE_TAG}" "${CI_IMAGE}:${CI_COMMIT_TAG}"
    - docker push "${CI_IMAGE}:${CI_COMMIT_TAG}"
  only:
    - tags