stages:
  - prepare
  - build
  - test
  - distribute
  - build_image
  - test_image
  - release_image
  - clean


image: registry.cnrgh.fr/images/sources/ibfj-bioinfo-analysis-r:latest


variables:
  DOCKER_DRIVER:        overlay2
  LANG:                 'en_US.UTF-8'
  DOCKER_REPO:          'registry.cnrgh.fr/$CI_PROJECT_NAMESPACE/contatester/'
  IMAGE_NAME:           'contatester'
  CONTATESTER_VERSION:  '1.0.0'
  USEQ_VERSION:         '9.0.7'

.active_python_venv:
  before_script:
    - source venv/bin/activate
    - export R_LIBS="$(pwd)/rlib:/ur/lib64/Rlibrary"
    - yum install -y libcurl openssl

.docker_jobs:
  image: docker
  tags:
    - dind
  cache:
    key: ${CI_PIPELINE_ID}-docker_lbi
    untracked: true
  # No var expansion as bash do see: https://www.trek10.com/blog/making-ci-easier-with-gitlab/
  before_script:
    - eval export TODAY=$(date +'%Y%m%d')
    - eval export CI_SHORT_COMMIT_SHA="${CI_COMMIT_SHA:0:8}"
    - eval export TEST_IMAGE_TAG="${TODAY}_${CI_SHORT_COMMIT_SHA}"
    - eval export IMAGE_FILE="contatester-${TEST_IMAGE_TAG}.tar.gz"
    - echo "${CI_JOB_TOKEN}" | docker login -u gitlab-ci-token --password-stdin registry.cnrgh.fr


prepare_python_env:
  stage: prepare
  tags:
    - nodind
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    untracked: true
    paths:
      - venv
      - rlib
      - USeq_${USEQ_VERSION}.zip
  artifacts:
    untracked: true
    paths:
      - venv
      - rlib
  before_script:
    - yum install -y libcurl-devel g++ openssl-devel
    - python3 -m venv venv
    - source venv/bin/activate
  script:
    - pip3 install setuptools wheel
    - pip3 install --upgrade pip
    - pip3 install --upgrade wheel
    - pip3 install --upgrade setuptools
    - ./install_useq.sh venv "${USEQ_VERSION}"
    - mkdir -p rlib
    - echo -e ".libPaths('$(pwd)/rlib')\noptions(repos = c(CRAN = 'https://cran.rstudio.com'))" > .Rprofile
    - export R_LIBS="$(pwd)/rlib:/ur/lib64/Rlibrary"
    - ./rPackageInstaller.r


build_contatester:
  stage: build
  extends: .active_python_venv
  artifacts:
    untracked: true
    paths:
      - dist/contatester-${CONTATESTER_VERSION}-py2.py3-none-any.whl
  script:
    - sed -r "/VERSION\s+=\s+'/s/[0-9\.]+/${CONTATESTER_VERSION}/g" setup.py
    - python3 setup.py clean
    - python3 setup.py bdist_wheel


test_all:
  stage: test
  extends: .active_python_venv
  artifacts:
   untracked: true
  script:
    - pip3 install dist/contatester-${CONTATESTER_VERSION}-py2.py3-none-any.whl
    - ./run_tests.sh 


coverage_contatester:
  stage: test
  extends: .active_python_venv
  artifacts:
    name: reports
    paths:
      - htmlcov/*
  script:
    - pip3 install coverage
    - python3 setup.py coverage


wheel_contatester:
  stage: distribute
  extends: .active_python_venv
  artifacts:
    name: wheel
    paths:
      - dist/contatester-${CONTATESTER_VERSION}-py2.py3-none-any.whl
  script:
    - python3 setup.py bdist_wheel


build_contatester_image:
  stage: build_image
  extends: .docker_jobs
  artifacts:
    name: docker_image
    paths:
      - ${CI_COMMIT_SHA}/image/contatester-*.tar.gz   # Artifacts can only exist in directories relative to the build directory
                                                      # Only predefined variables can be used which exclude variables define in script section
    expire_in: 3d
  script:
    - mkdir -p ${CI_COMMIT_SHA}/image/
    - archive_file="contatester_src_$(date +'%s').tar.gz" # prevent docker cache
    - |
      tar czf "${archive_file}" rlib dist/contatester-${CONTATESTER_VERSION}-py2.py3-none-any.whl ./install_useq.sh
    - |
      docker build \
              --build-arg ARCHIVE_FILE="${archive_file}" \
              --build-arg CONTATESTER_VERSION="${CONTATESTER_VERSION}" \
              --build-arg USEQ_VERSION="${USEQ_VERSION}" \
              -t "${DOCKER_REPO}${IMAGE_NAME}:${TEST_IMAGE_TAG}" .
    - docker save "${DOCKER_REPO}${IMAGE_NAME}:${TEST_IMAGE_TAG}" | gzip -c > "${CI_COMMIT_SHA}/image/${IMAGE_FILE}"
    - du -sh ${CI_COMMIT_SHA}/image/contatester-*.tar.gz


test_contatester_image:
  stage: test_image
  extends: .docker_jobs
  script:
    - docker load --input "${CI_COMMIT_SHA}/image/${IMAGE_FILE}"
    - |
      docker run --volume $(pwd)/data_examples/test_1.vcf.gz:/test_1.vcf.gz \
                 --volume $(pwd)/data_examples/test_2.vcf.gz:/test_2.vcf.gz \
                 "${DOCKER_REPO}${IMAGE_NAME}:${TEST_IMAGE_TAG}" -l data_examples/vcfs_list.txt

master_image:
  stage: release_image
  extends: .docker_jobs
  script:
    - docker load --input "${CI_COMMIT_SHA}/image/${IMAGE_FILE}"
    - docker tag  "${DOCKER_REPO}${IMAGE_NAME}:${TEST_IMAGE_TAG}" ${DOCKER_REPO}${IMAGE_NAME}:latest
    - docker push "${DOCKER_REPO}${IMAGE_NAME}:latest"
  only:
    - master


release_image:
  stage: release_image
  extends: .docker_jobs
  script:
    - docker load --input "${CI_COMMIT_SHA}/image/${IMAGE_FILE}"
    - docker tag  "${DOCKER_REPO}${IMAGE_NAME}:${TEST_IMAGE_TAG}" "${DOCKER_REPO}${IMAGE_NAME}:${CONTATESTER_VERSION}"
    - docker push "$${DOCKER_REPO}{IMAGE_NAME}:${CONTATESTER_VERSION}"
  only:
    - tags


remove image:
  stage: clean
  extends: .docker_jobs
  when: always
  script:
    - docker images
    # Stop any running containers, if they are not running anymore (since its not a run -d), ignore errors about that.
    - docker rm -f "${DOCKER_REPO}${IMAGE_NAME}:${TEST_IMAGE_TAG}" ${IMAGE_NAME} || true
    # Remove pulled images
    - docker rmi -f "${DOCKER_REPO}${IMAGE_NAME}:${TEST_IMAGE_TAG}" || true
    # Remove all images (current et previouslys build container missed) [Optional]
    #- docker images | awk -v pattern="${DOCKER_REPO}${IMAGE_NAME}" '{if( $1 ~ /^pattern/ ){ print $1":"$2; system(docker rmi -f $1":"$2) }}'


docker remove all temp files:
  stage: clean
  when: always
  cache:
    key: ${CI_PIPELINE_ID}-docker_lbi
  script:
    - rm -fr ${CI_COMMIT_SHA}/


python remove all temp files:
  stage: clean
  when: always
  cache:
    key: ${CI_PIPELINE_ID}-py_lbi
  script:
    - rm -fr .eggs .pytest_cache/ build/ dist/ htmlcov/ src/contatester.egg-info/
    - find . -name __pycache__ | xargs rm -fr
